### ISSUE TITLE
 JOIN_VOICE_CALL_ERROR -> 'transport'

### ISSUE THREAD

**Issue by Shahjahan123** [pytgcalls/pytgcalls#159] opened 2022-07-21 20:06 UTC
I'm trying to join voice chat  which is running but is pytgcalls showing an error 

JOIN_VOICE_CALL_ERROR -> 'transport'
pytgcalls: joinCallRequestResult -> {"transport":null}
pytgcalls: joinCallError -> Error: No active voice chat found on xxxxx

when I try to join a test channel that is mine it joins, but when try to join other channels it shows this error.

![2022-07-22 01_01_50-Clipboard](https://user-images.githubusercontent.com/46046704/180306206-fa5a951d-a0d5-46b7-b150-5803010e3fb3.png)

**Comment by Laky-64** [comment] 2022-08-06 17:47
No Transport found.... Mhhh, do you have a reproducibile group where i can try?

**Comment by Shahjahan123** [comment] 2022-08-06 17:51
> No Transport found.... Mhhh, do you have a reproducibile group where i can try?

My Code
https://nekobin.com/coyuqeqoqe

also tried With example code

**Comment by Laky-64** [comment] 2022-08-06 17:54
Yes, but not happens on all groups, can you tell me where i can try?

**Comment by Shahjahan123** [comment] 2022-08-06 17:58
> Yes, but it doesn't happen on all groups, can you tell me where I can try?

![image](https://user-images.githubusercontent.com/46046704/183260474-68b89d88-ef46-46b5-8316-5eea003f9609.png)


this is chat id: -1001566073593

**Comment by Laky-64** [comment] 2022-08-06 18:02
That is a private channel

**Comment by Shahjahan123** [comment] 2022-08-06 18:02
voice chat is active there

**Comment by Laky-64** [comment] 2022-08-06 18:03
Ok, can i join on it? Can you gimme the invite link?

**Comment by Shahjahan123** [comment] 2022-08-06 18:06
there is vc is open same error here
-1001599711149

**Comment by Shahjahan123** [comment] 2022-08-06 18:14
this one is not private

**Comment by Shahjahan123** [comment] 2022-08-06 18:25
> Ok, can i join on it? Can you gimme the invite link?

invite link is not there 

you can try new one

**Comment by Laky-64** [comment] 2022-08-07 15:01
With the latest beta now this error is handled
https://github.com/pytgcalls/pytgcalls/commit/7f2d8bde9d94ab28bb9b50efccafb8e5f724f7b9

**Comment by Shahjahan123** [comment] 2022-08-07 21:13
I also tried the latest beta version
Name: py-tgcalls
Version: 0.9.2b1

**Comment by Shahjahan123** [comment] 2022-08-08 13:06
that transport null is gone but a new "transport update error" is comming

![2022-08-08 18_04_18-Clipboard](https://user-images.githubusercontent.com/46046704/183424763-323b17ec-fb8c-43d8-a7cf-d03833174f1d.png)

**Comment by Laky-64** [comment] 2022-08-08 13:11
That is because you need to be unmuted on that channel before playing

**Comment by Shahjahan123** [comment] 2022-08-08 13:49
the exception is not working for this, I just want to listen, I have an empty mp3 file for this

**Comment by Laky-64** [comment] 2022-08-08 13:52
In that case you don't need to use pytgcalls, but this 
https://docs.pyrogram.org/telegram/functions/phone/get-group-call-stream-channels?highlight=groupcallstreamchannel

**Comment by Shahjahan123** [comment] 2022-08-08 13:59
No, I want to join the VC,  with pytgcalls, what should i do with that exception

**Comment by Laky-64** [comment] 2022-08-08 14:00
The userbot will join, but without playing the song

**Comment by Shahjahan123** [comment] 2022-08-08 14:05
yes this is what i want, but how can i use that exception for unmuting

**Comment by Laky-64** [comment] 2022-08-08 15:02
Just use an try & catch

**Comment by Laky-64** [comment] 2022-08-08 15:03
Then re-call the join_group_call

**Comment by Laky-64** [comment] 2022-08-12 01:02
I will close this issue and mark as resolved

**Closed by Laky-64** 2022-08-12 01:02 UTC
Labels: Investigation Needed
